### PR TITLE
fix(pack): now ignoring file useless for dist

### PR DESCRIPTION
**Pull request by kopax**

### CODE REVIEW

**Comment by kopax** [comment]
Inspired from: 

- https://github.com/bufferoverflow/verdaccio-gitlab/pull/23 
- https://github.com/idangozlan/verdaccio-bitbucket/blob/master/src/cache.js

Test: OK

## How to test

Use the test release version on `npm`:

```sh
$ npm install -g verdaccio-ldap-node-cache@2.1.6
```

You will need at least to rename your `ldap` config in your `config.yaml`:

```yaml
auth:
  # Note: to people who want to test it
  # this MUST be the suffix of the module so here it is ldap-node-cache instead of ldap 
  ldap-node-cache:
    type: ldap
    authCache:
      enabled: true # default
      ttl: 350 # default
```

It is also possible to test with Docker:

```Dockerfile
FROM verdaccio/verdaccio:3
RUN yarn add verdaccio-ldap-node-cache@2.1.6
```

**Comment by Alexandre-io** [comment]
ty let me review your PR

**Comment by Alexandre-io** [comment]
@kopax node-ldapauth-fork provide a "cache" option, why do not use it ?

**Comment by kopax** [comment]
I have not even read that part. I followed the path from bitbucket and Gitlab. I personally wanted to add redis. Is this release already? I am not seing `master` updated with the changes.

I tried to get support and finally decided to do this, I would have not if I knew. @Alexandre-io Is this already implemented? 

If it is, how do you use it ?

**Comment by calledt** [comment]
@Alexandre-io node-ldapauth-fork "cache" not work properly in this plugin. 

every time authenticate invoke will create new instance of node-ldapauth-fork

https://github.com/Alexandre-io/verdaccio-ldap/blob/e4ed38cb98ccad9a4334a4e3c28f47f1b04ff9e8/index.js#L32

and node-ldapauth-fork stored cache in it's instance

https://github.com/vesse/node-ldapauth-fork/blob/78b7fca0fa85e8bd4164f011d4a319a3febcf788/lib/ldapauth.js#L78

**Comment by kopax** [comment]
We need to find a solution, how do you want me to proceed? Should I move the instance creation?

I can see the latest version does not solved it either: https://github.com/Alexandre-io/verdaccio-ldap/blob/2.3.0/index.js#L32

**Comment by kopax** [comment]
@Alexandre-io I have also made a fixed version using `node-ldapauth-fork` using @calledT recommendation.  see #41

**Pull request merged**
