### PR TITLE
fix(groups): support memberOf

### LINKED ISSUE #21: version 1.4.0 breaks LDAP authentication by group
I just updated from `1.3.0` to `1.4.0` and could no longer access any packages from my verdaccio server.

I get errors like:

`"status":403,"error":"user <user> is not allowed to access package <package>"`

My verdaccio `config.yaml` is setup to use the ldap groups to control access, something like:

```
packages:
  '@*/*':
    # scoped packages
    access: <ldap-group>
    publish: <ldap-group>
    proxy: npmjs
```

I downgraded back to `1.3.0` and everything started working again, so definitely looks like something broke in `1.4.0`

### PR DESCRIPTION
**Pull request by STRML**
This was not properly parsing groups back from ldapauth-fork.

Fixes #21

### CODE REVIEW

**Comment by jharris4** [comment]
I have tested this PR, and can confirm that it fixes #21

**Comment by kopax** [comment]
Hi, ca we release this?

I have build an image with this fix and tested it out : 

```Dockerfile
FROM node:10.1.0-alpine

ENV VERDACCION_VERSION=${VERDACCION_VERSION:-2.7.4}

# ENV VERDACCION_LDAP_VERSION=${VERDACCION_LDAP_VERSION:-1.4.0}
ENV VERDACCION_LDAP_FIX_COMMIT=27c6d7b7c3efab111955d36a239034695898b111

ENV VERDACCIO_PORT=${VERDACCIO_PORT:-4873}
ENV VERDACCIO_PROTOCOL ${VERDACCIO_PROTOCOL:-http}

RUN apk --no-cache add openssl && \
    wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 && \
    chmod +x /usr/local/bin/dumb-init && \
    apk del openssl

ENV APPDIR /usr/local/app

# WORKDIR $APPDIR
# ADD . $APPDIR

ENV NODE_ENV=production

# For the ldap fix we need git
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN npm config set registry http://registry.npmjs.org/ && \
    npm install -g verdaccio@${VERDACCION_VERSION} && \

    # We use ldap fix
		#npm install -g verdaccio-ldap@${VERDACCION_LDAP_VERSION}
		npm install -g git+https://github.com/STRML/verdaccio-ldap.git#${VERDACCION_LDAP_FIX_COMMIT}

RUN mkdir -p /verdaccio/storage /verdaccio/conf

ADD ldap/config.yaml /verdaccio/conf/config.yaml

RUN addgroup -S verdaccio && adduser -S -G verdaccio verdaccio && \
#    chown -R verdaccio:verdaccio "$APPDIR" && \
    chown -R verdaccio:verdaccio /verdaccio

USER verdaccio

EXPOSE $VERDACCIO_PORT

VOLUME ["/verdaccio"]

ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]

CMD verdaccio --config /verdaccio/conf/config.yaml --listen $VERDACCIO_PROTOCOL://0.0.0.0:${VERDACCIO_PORT}
```

My configuration looks as follow : 

```yml
storage: /verdaccio/storage

auth:
  ldap:
    type: ldap
    groupNameAttribute: 'cn'
    client_options:
      url: "ldap://ldap.example.com"
      adminDn: "cn=readonly,dc=someorg,dc=com"
      adminPassword: "someorg123"
      searchBase: "dc=someorg,dc=com"
      # searchFilter: "(&(uid={{username}})(memberOf=cn=npm_users,ou=groups,dc=someorg,dc=com))"
      searchFilter: "(uid={{username}})"
      # # If you are using groups, this is also needed
      groupDnProperty: 'cn'
      groupSearchBase: 'ou=groups,dc=example,dc=com'
      # groupSearchFilter: '(memberUid={{dn}})'

      # If you have memberOf support on your ldap
      searchAttributes: ['*', 'memberOf']
      # Else, if you don't (use one or the other):
      # groupSearchFilter: '(memberUid={{dn}})'

      # Optional
      cache: False
      # searchAttributes:
#         - "*"
#        - memberOf
      tlsOptions:
        rejectUnauthorized: False
    max_users: -1
  htpasswd:
    file: ./htpasswd
#   # Maximum amount of users allowed to register, defaults to "+inf".
#   # You can set this to -1 to disable registration.
#   # currently used only for deployment accounts
    max_users: 2

# a list of other known repositories we can talk to

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@someorg/*':
    # scoped packages
    access: npm_someorg_users
    publish: npm_someorg_users
#    proxy: npmjs

  '@*/*':
    # scoped packages
    access: npm_users
    publish: npm_users

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: npm_users

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: npm_users

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  # - {type: file, path: /verdaccio.log, level: info}
web:
  enable: true
  title: Redacted
```

I have been not able to authenticate with 1.4.0 yet.

The command is pending with:

```bash
$ npm adduser --registry  http://dev-npm.someorg.com
Username: me
Password: 
Email: (this IS public) me@someorg.com
```

While the server log hang with:

```bash
verdaccio_1  |  warn --- config file  - /verdaccio/conf/config.yaml
verdaccio_1  |  warn --- http address - http://0.0.0.0:4873/ - verdaccio/2.7.4
verdaccio_1  | (node:8) ExperimentalWarning: The fs.promises API is experimental
verdaccio_1  |  http <-- 404, user: undefined(172.18.0.1 via 172.17.0.1), req: 'POST /-/v1/login', bytes: 21/150
verdaccio_1  |  http <-- 200, user: undefined(172.18.0.1 via 172.17.0.1), req: 'PUT /-/user/org.couchdb.user:dka', bytes: 125/0
verdaccio_1  |  http <-- 409, user: undefined(172.18.0.1 via 172.17.0.1), req: 'PUT /-/user/org.couchdb.user:dka', error: this user already exists
verdaccio_1  |  http <-- 200, user: undefined(172.18.0.1 via 172.17.0.1), req: 'GET /-/user/org.couchdb.user:dka?write=true', bytes: 0/53
verdaccio_1  |  http <-- 200, user: undefined(172.18.0.1 via 172.17.0.1), req: 'PUT /-/user/org.couchdb.user:dka/-rev/undefined', bytes: 0/0

```

I have never been able to make ldap work with group, is there anyway I can get some friend to help me out?

Should this be used only with verdaccio 3.0.0-beta?

**Comment by jharris4** [comment]
@kopax we've been using verdaccio with ldap and group authorization for months now. It was working fine up until version 1.4.0, and this PR seems to fix the problem introduced in 1.4.0.

 In case it helps you, here is what our verdaccio `config.yaml` looks like:

```
listen: http://0.0.0.0:4873

storage: ./storage

auth:
  ldap:
    type: ldap
    groupNameAttribute: 'cn'
    client_options:
      url: "ldap://<server_name_here>"
      adminDn: "uid=<user_here>,cn=sysaccounts,cn=etc,dc=<domain_here>,dc=com"
      adminPassword: "<password_here>"
      searchBase: "cn=users,cn=accounts,dc=<domain_here>,dc=com"
      searchFilter: "(uid={{username}})"
      cache: False
      searchAttributes:
        - "*"
        - memberOf
      tlsOptions:
        rejectUnauthorized: False

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: verdaccio
    publish: verdaccio
    proxy: npmjs

  '**':
    access: verdaccio
    publish: verdaccio
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: info}

```

With the above config, we are able to add ldap users to the `verdaccio` group, which automatically gives them access access or publish any package through our verdaccio server.

**Comment by kopax** [comment]
Thanks JHarris, there is a 2.0.0 release out by the author I think it is supposed to fix 1.4.0. I will try to setup using your configuration 1.3.0 and 2.0.0, there is no reason.

It would be nice to add a way to logs the ldap groups after retrieval, I have the feeling that even in 1.3.0, groups membership is ignored.

**Pull request merged**
